export const KIOSK_STATES = {
    IDLE: "IDLE",

    SCAN: "SCAN",
    STUDENT_DASHBOARD: "STUDENT_DASHBOARD",

    LOCKER_SELECT: "LOCKER_SELECT",
    PAYMENT: "PAYMENT",
    PROCESSING: "PROCESSING",

    ACTIVE_SESSION: "ACTIVE_SESSION",
    DONE: "DONE",

    ERROR: "ERROR",
};
